name: Build application
on:
  push:
    branches:
      - 'main'
jobs:
  on_build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'hola mundo'
  