name: Build application
on:
  push:
    branches:
      - 'main'
runs-on: ubuntu-latest
jobs:
  checkout:
    name: Checkout Code
    steps:
      - uses: actions/checkout@v3
  setup:
    name: Setup environment
    needs: [checkout]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'v18.8.0'
      - run: node -v
  run-tests:
    name: Run unit tests
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - run: yarn test
  tests-done:
    name: Tests Done
    needs: [run-tests]
    steps:
      - run : echo 'All good!'
  deploy: 
    name: Deployment
    needs: [tests-done]
    steps:
      - run : echo 'DEPLOY!!! 🚢'
    
  