name: Build application
on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - syncronize


jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'v18.8.0'
      - run: node -v
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - run: yarn test
  tests-done:
    name: Tests Done
    runs-on: ubuntu-latest
    needs: [run-tests]
    steps:
      - run : echo 'All good!'
  deploy: 
    name: Deployment
    runs-on: ubuntu-latest
    needs: [tests-done]
    steps:
      - run : echo 'DEPLOY!!! 🚢'
    
  